name: Pull Request
on:
  pull_request:
    branches:
      - master

env:
  GO_VERSION: "^1.15.2"
  COMPONENT_NAME: espejo

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_jsonnet
          - lint_yaml
    steps:
      - uses: actions/checkout@v2
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.COMPONENT_NAME }}
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Compile component
        run: |
          GO111MODULE="on" go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
          cd ${{ env.COMPONENT_NAME }}
          make compile
      - name: Determining tests to run
        id: determine-tests
        run: |
          if [ -f "${{ env.COMPONENT_NAME }}/tests/go/go.mod" ]; then echo "::set-output name=RUN_GO_TESTS::true" ; fi
          if [ -d "${{ env.COMPONENT_NAME }}/tests/conftest" ]; then echo "::set-output name=RUN_CONFTESTS::true" ; fi
      - name: Run Unit tests
        run: cd ${{ env.COMPONENT_NAME }} && make test_go
        if: ${{ steps.determine-tests.outputs.RUN_GO_TESTS == 'true' }}
      - name: Run Conftest tests
        run: cd ${{ env.COMPONENT_NAME }} && make test_conftest
        if: ${{ steps.determine-tests.outputs.RUN_CONFTESTS == 'true' }}
