name: Pull Request
on:
  pull_request:
    branches:
      - master

env:
  GO_VERSION: "^1.15.2"
  COMPONENT_NAME: espejo

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_jsonnet
          - lint_yaml
    steps:
      - uses: actions/checkout@v2
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.COMPONENT_NAME }}
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Compile component
        run: cd ${{ env.COMPONENT_NAME }} && make compile
      - name: Run Unit tests
        run: cd ${{ env.COMPONENT_NAME }} && make test_go
      - name: Run Conftest tests
        run: cd ${{ env.COMPONENT_NAME }} && make test_conftest
